# coding: utf-8

"""
    Kubeapps API

    [![CircleCI](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main.svg?style=svg)](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main)   [Kubeapps](https://github.com/vmware-tanzu/kubeapps) is a web-based UI for deploying and managing applications in Kubernetes clusters.   Note: this API documentation is still in an initial stage and is subject to change. Before coupling to it, please [drop us an issue](https://github.com/vmware-tanzu/kubeapps/issues/new/choose) or reach us [via Slack](https://kubernetes.slack.com/messages/kubeapps) to know more about your use case and see how we can assist you.  #### Developer Documentation  - The [Kubeapps Architecture Overview](https://kubeapps.dev/docs/latest/background/architecture/).  - The [Kubeapps Developer Documentation](https://kubeapps.dev/docs/latest/reference/developer/) for instructions on setting up the developer environment for developing on Kubeapps and its components.  - The [Kubeapps Build Guide](https://kubeapps.dev/docs/latest/reference/developer/build/) for instructions on setting up the build environment and building Kubeapps from source.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.resources_service_api import ResourcesServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestResourcesServiceApi(unittest.TestCase):
    """ResourcesServiceApi unit test stubs"""

    def setUp(self):
        self.api = ResourcesServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_resources_service_can_i(self):
        """Test case for resources_service_can_i

        """
        pass

    def test_resources_service_check_namespace_exists(self):
        """Test case for resources_service_check_namespace_exists

        """
        pass

    def test_resources_service_create_namespace(self):
        """Test case for resources_service_create_namespace

        """
        pass

    def test_resources_service_create_secret(self):
        """Test case for resources_service_create_secret

        """
        pass

    def test_resources_service_get_namespace_names(self):
        """Test case for resources_service_get_namespace_names

        """
        pass

    def test_resources_service_get_resources(self):
        """Test case for resources_service_get_resources

        """
        pass

    def test_resources_service_get_secret_names(self):
        """Test case for resources_service_get_secret_names

        """
        pass

    def test_resources_service_get_service_account_names(self):
        """Test case for resources_service_get_service_account_names

        """
        pass


if __name__ == '__main__':
    unittest.main()
