# coding: utf-8

"""
    Kubeapps API

    [![Main Pipeline](https://github.com/vmware-tanzu/kubeapps/actions/workflows/kubeapps-main.yaml/badge.svg)](https://github.com/vmware-tanzu/kubeapps/actions/workflows/kubeapps-main.yaml)    [Kubeapps](https://github.com/vmware-tanzu/kubeapps) is a web-based UI for deploying and managing applications in Kubernetes clusters.    Note: this API documentation is still in an initial stage and is subject to change. Before coupling to it, please [drop us an issue](https://github.com/vmware-tanzu/kubeapps/issues/new/choose) or reach us [via Slack](https://kubernetes.slack.com/messages/kubeapps) to know more about your use case and see how we can assist you.  #### Developer Documentation  - The [Kubeapps architecture overview](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/background/architecture.md).  - The [Kubeapps Developer Documentation](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/reference/developer/README.md) for instructions on setting up the developer environment for developing on Kubeapps and its components.  - The [Kubeapps Build Guide](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/reference/developer/build.md) for instructions on setting up the build environment and building Kubeapps from source.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kubeapps_client
from kubeapps_client.api.packages_service_api import PackagesServiceApi  # noqa: E501
from kubeapps_client.rest import ApiException


class TestPackagesServiceApi(unittest.TestCase):
    """PackagesServiceApi unit test stubs"""

    def setUp(self):
        self.api = PackagesServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_packages_service_create_installed_package(self):
        """Test case for packages_service_create_installed_package

        """
        pass

    def test_packages_service_delete_installed_package(self):
        """Test case for packages_service_delete_installed_package

        """
        pass

    def test_packages_service_get_available_package_detail(self):
        """Test case for packages_service_get_available_package_detail

        """
        pass

    def test_packages_service_get_available_package_metadatas(self):
        """Test case for packages_service_get_available_package_metadatas

        """
        pass

    def test_packages_service_get_available_package_summaries(self):
        """Test case for packages_service_get_available_package_summaries

        """
        pass

    def test_packages_service_get_available_package_versions(self):
        """Test case for packages_service_get_available_package_versions

        """
        pass

    def test_packages_service_get_installed_package_detail(self):
        """Test case for packages_service_get_installed_package_detail

        """
        pass

    def test_packages_service_get_installed_package_resource_refs(self):
        """Test case for packages_service_get_installed_package_resource_refs

        """
        pass

    def test_packages_service_get_installed_package_summaries(self):
        """Test case for packages_service_get_installed_package_summaries

        """
        pass

    def test_packages_service_update_installed_package(self):
        """Test case for packages_service_update_installed_package

        """
        pass


if __name__ == '__main__':
    unittest.main()
