from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from kubeapps_client.api.flux_v2_packages_service_api import FluxV2PackagesServiceApi
from kubeapps_client.api.flux_v2_repositories_service_api import FluxV2RepositoriesServiceApi
from kubeapps_client.api.helm_packages_service_api import HelmPackagesServiceApi
from kubeapps_client.api.helm_repositories_service_api import HelmRepositoriesServiceApi
from kubeapps_client.api.kapp_controller_packages_service_api import KappControllerPackagesServiceApi
from kubeapps_client.api.kapp_controller_repositories_service_api import KappControllerRepositoriesServiceApi
from kubeapps_client.api.packages_service_api import PackagesServiceApi
from kubeapps_client.api.plugins_service_api import PluginsServiceApi
from kubeapps_client.api.repositories_service_api import RepositoriesServiceApi
from kubeapps_client.api.resources_service_api import ResourcesServiceApi
