# coding: utf-8

"""
    Kubeapps API

    [![CircleCI](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main.svg?style=svg)](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main)   [Kubeapps](https://github.com/vmware-tanzu/kubeapps) is a web-based UI for deploying and managing applications in Kubernetes clusters.   Note: this API documentation is still in an initial stage and is subject to change. Before coupling to it, please [drop us an issue](https://github.com/vmware-tanzu/kubeapps/issues/new/choose) or reach us [via Slack](https://kubernetes.slack.com/messages/kubeapps) to know more about your use case and see how we can assist you.  #### Developer Documentation  - The [Kubeapps Architecture Overview](https://kubeapps.dev/docs/latest/background/architecture/).  - The [Kubeapps Developer Documentation](https://kubeapps.dev/docs/latest/reference/developer/) for instructions on setting up the developer environment for developing on Kubeapps and its components.  - The [Kubeapps Build Guide](https://kubeapps.dev/docs/latest/reference/developer/build/) for instructions on setting up the build environment and building Kubeapps from source.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateInstalledPackageRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'installed_package_ref': 'AReferenceUniquelyIdentifyingTheInstalledPackageBeingUpdatedRequired',
        'pkg_version_reference': 'V1alpha1VersionReference',
        'values': 'str',
        'reconciliation_options': 'V1alpha1ReconciliationOptions'
    }

    attribute_map = {
        'installed_package_ref': 'installedPackageRef',
        'pkg_version_reference': 'pkgVersionReference',
        'values': 'values',
        'reconciliation_options': 'reconciliationOptions'
    }

    def __init__(self, installed_package_ref=None, pkg_version_reference=None, values=None, reconciliation_options=None):  # noqa: E501
        """UpdateInstalledPackageRequest - a model defined in Swagger"""  # noqa: E501
        self._installed_package_ref = None
        self._pkg_version_reference = None
        self._values = None
        self._reconciliation_options = None
        self.discriminator = None
        if installed_package_ref is not None:
            self.installed_package_ref = installed_package_ref
        if pkg_version_reference is not None:
            self.pkg_version_reference = pkg_version_reference
        if values is not None:
            self.values = values
        if reconciliation_options is not None:
            self.reconciliation_options = reconciliation_options

    @property
    def installed_package_ref(self):
        """Gets the installed_package_ref of this UpdateInstalledPackageRequest.  # noqa: E501


        :return: The installed_package_ref of this UpdateInstalledPackageRequest.  # noqa: E501
        :rtype: AReferenceUniquelyIdentifyingTheInstalledPackageBeingUpdatedRequired
        """
        return self._installed_package_ref

    @installed_package_ref.setter
    def installed_package_ref(self, installed_package_ref):
        """Sets the installed_package_ref of this UpdateInstalledPackageRequest.


        :param installed_package_ref: The installed_package_ref of this UpdateInstalledPackageRequest.  # noqa: E501
        :type: AReferenceUniquelyIdentifyingTheInstalledPackageBeingUpdatedRequired
        """

        self._installed_package_ref = installed_package_ref

    @property
    def pkg_version_reference(self):
        """Gets the pkg_version_reference of this UpdateInstalledPackageRequest.  # noqa: E501


        :return: The pkg_version_reference of this UpdateInstalledPackageRequest.  # noqa: E501
        :rtype: V1alpha1VersionReference
        """
        return self._pkg_version_reference

    @pkg_version_reference.setter
    def pkg_version_reference(self, pkg_version_reference):
        """Sets the pkg_version_reference of this UpdateInstalledPackageRequest.


        :param pkg_version_reference: The pkg_version_reference of this UpdateInstalledPackageRequest.  # noqa: E501
        :type: V1alpha1VersionReference
        """

        self._pkg_version_reference = pkg_version_reference

    @property
    def values(self):
        """Gets the values of this UpdateInstalledPackageRequest.  # noqa: E501

        An optional serialized values string to be included when templating a package in the format expected by the plugin. Included when the backend format doesn't use secrets or configmaps for values or supports both. These values are layered on top of any values refs above, when relevant.  # noqa: E501

        :return: The values of this UpdateInstalledPackageRequest.  # noqa: E501
        :rtype: str
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this UpdateInstalledPackageRequest.

        An optional serialized values string to be included when templating a package in the format expected by the plugin. Included when the backend format doesn't use secrets or configmaps for values or supports both. These values are layered on top of any values refs above, when relevant.  # noqa: E501

        :param values: The values of this UpdateInstalledPackageRequest.  # noqa: E501
        :type: str
        """

        self._values = values

    @property
    def reconciliation_options(self):
        """Gets the reconciliation_options of this UpdateInstalledPackageRequest.  # noqa: E501


        :return: The reconciliation_options of this UpdateInstalledPackageRequest.  # noqa: E501
        :rtype: V1alpha1ReconciliationOptions
        """
        return self._reconciliation_options

    @reconciliation_options.setter
    def reconciliation_options(self, reconciliation_options):
        """Sets the reconciliation_options of this UpdateInstalledPackageRequest.


        :param reconciliation_options: The reconciliation_options of this UpdateInstalledPackageRequest.  # noqa: E501
        :type: V1alpha1ReconciliationOptions
        """

        self._reconciliation_options = reconciliation_options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateInstalledPackageRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateInstalledPackageRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
