# coding: utf-8

"""
    Kubeapps API

    [![CircleCI](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main.svg?style=svg)](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main)   [Kubeapps](https://github.com/vmware-tanzu/kubeapps) is a web-based UI for deploying and managing applications in Kubernetes clusters.   Note: this API documentation is still in an initial stage and is subject to change. Before coupling to it, please [drop us an issue](https://github.com/vmware-tanzu/kubeapps/issues/new/choose) or reach us [via Slack](https://kubernetes.slack.com/messages/kubeapps) to know more about your use case and see how we can assist you.  #### Developer Documentation  - The [Kubeapps Architecture Overview](https://kubeapps.dev/docs/latest/background/architecture/).  - The [Kubeapps Developer Documentation](https://kubeapps.dev/docs/latest/reference/developer/) for instructions on setting up the developer environment for developing on Kubeapps and its components.  - The [Kubeapps Build Guide](https://kubeapps.dev/docs/latest/reference/developer/build/) for instructions on setting up the build environment and building Kubeapps from source.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdatePackageRepositoryRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'package_repo_ref': 'AReferenceUniquelyIdentifyingThePackageRepositoryBeingUpdatedTheOnlyRequiredField',
        'url': 'str',
        'description': 'str',
        'interval': 'str',
        'tls_config': 'V1alpha1PackageRepositoryTlsConfig',
        'auth': 'V1alpha1PackageRepositoryAuth',
        'custom_detail': 'ProtobufAny'
    }

    attribute_map = {
        'package_repo_ref': 'packageRepoRef',
        'url': 'url',
        'description': 'description',
        'interval': 'interval',
        'tls_config': 'tlsConfig',
        'auth': 'auth',
        'custom_detail': 'customDetail'
    }

    def __init__(self, package_repo_ref=None, url=None, description=None, interval=None, tls_config=None, auth=None, custom_detail=None):  # noqa: E501
        """UpdatePackageRepositoryRequest - a model defined in Swagger"""  # noqa: E501
        self._package_repo_ref = None
        self._url = None
        self._description = None
        self._interval = None
        self._tls_config = None
        self._auth = None
        self._custom_detail = None
        self.discriminator = None
        if package_repo_ref is not None:
            self.package_repo_ref = package_repo_ref
        if url is not None:
            self.url = url
        if description is not None:
            self.description = description
        if interval is not None:
            self.interval = interval
        if tls_config is not None:
            self.tls_config = tls_config
        if auth is not None:
            self.auth = auth
        if custom_detail is not None:
            self.custom_detail = custom_detail

    @property
    def package_repo_ref(self):
        """Gets the package_repo_ref of this UpdatePackageRepositoryRequest.  # noqa: E501


        :return: The package_repo_ref of this UpdatePackageRepositoryRequest.  # noqa: E501
        :rtype: AReferenceUniquelyIdentifyingThePackageRepositoryBeingUpdatedTheOnlyRequiredField
        """
        return self._package_repo_ref

    @package_repo_ref.setter
    def package_repo_ref(self, package_repo_ref):
        """Sets the package_repo_ref of this UpdatePackageRepositoryRequest.


        :param package_repo_ref: The package_repo_ref of this UpdatePackageRepositoryRequest.  # noqa: E501
        :type: AReferenceUniquelyIdentifyingThePackageRepositoryBeingUpdatedTheOnlyRequiredField
        """

        self._package_repo_ref = package_repo_ref

    @property
    def url(self):
        """Gets the url of this UpdatePackageRepositoryRequest.  # noqa: E501

        URL identifying the package repository location.  # noqa: E501

        :return: The url of this UpdatePackageRepositoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this UpdatePackageRepositoryRequest.

        URL identifying the package repository location.  # noqa: E501

        :param url: The url of this UpdatePackageRepositoryRequest.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def description(self):
        """Gets the description of this UpdatePackageRepositoryRequest.  # noqa: E501

        A user-provided description.  # noqa: E501

        :return: The description of this UpdatePackageRepositoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdatePackageRepositoryRequest.

        A user-provided description.  # noqa: E501

        :param description: The description of this UpdatePackageRepositoryRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def interval(self):
        """Gets the interval of this UpdatePackageRepositoryRequest.  # noqa: E501


        :return: The interval of this UpdatePackageRepositoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this UpdatePackageRepositoryRequest.


        :param interval: The interval of this UpdatePackageRepositoryRequest.  # noqa: E501
        :type: str
        """

        self._interval = interval

    @property
    def tls_config(self):
        """Gets the tls_config of this UpdatePackageRepositoryRequest.  # noqa: E501


        :return: The tls_config of this UpdatePackageRepositoryRequest.  # noqa: E501
        :rtype: V1alpha1PackageRepositoryTlsConfig
        """
        return self._tls_config

    @tls_config.setter
    def tls_config(self, tls_config):
        """Sets the tls_config of this UpdatePackageRepositoryRequest.


        :param tls_config: The tls_config of this UpdatePackageRepositoryRequest.  # noqa: E501
        :type: V1alpha1PackageRepositoryTlsConfig
        """

        self._tls_config = tls_config

    @property
    def auth(self):
        """Gets the auth of this UpdatePackageRepositoryRequest.  # noqa: E501


        :return: The auth of this UpdatePackageRepositoryRequest.  # noqa: E501
        :rtype: V1alpha1PackageRepositoryAuth
        """
        return self._auth

    @auth.setter
    def auth(self, auth):
        """Sets the auth of this UpdatePackageRepositoryRequest.


        :param auth: The auth of this UpdatePackageRepositoryRequest.  # noqa: E501
        :type: V1alpha1PackageRepositoryAuth
        """

        self._auth = auth

    @property
    def custom_detail(self):
        """Gets the custom_detail of this UpdatePackageRepositoryRequest.  # noqa: E501


        :return: The custom_detail of this UpdatePackageRepositoryRequest.  # noqa: E501
        :rtype: ProtobufAny
        """
        return self._custom_detail

    @custom_detail.setter
    def custom_detail(self, custom_detail):
        """Sets the custom_detail of this UpdatePackageRepositoryRequest.


        :param custom_detail: The custom_detail of this UpdatePackageRepositoryRequest.  # noqa: E501
        :type: ProtobufAny
        """

        self._custom_detail = custom_detail

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdatePackageRepositoryRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdatePackageRepositoryRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
