# coding: utf-8

"""
    Kubeapps API

    [![Main Pipeline](https://github.com/vmware-tanzu/kubeapps/actions/workflows/kubeapps-main.yaml/badge.svg)](https://github.com/vmware-tanzu/kubeapps/actions/workflows/kubeapps-main.yaml)    [Kubeapps](https://github.com/vmware-tanzu/kubeapps) is a web-based UI for deploying and managing applications in Kubernetes clusters.    Note: this API documentation is still in an initial stage and is subject to change. Before coupling to it, please [drop us an issue](https://github.com/vmware-tanzu/kubeapps/issues/new/choose) or reach us [via Slack](https://kubernetes.slack.com/messages/kubeapps) to know more about your use case and see how we can assist you.  #### Developer Documentation  - The [Kubeapps architecture overview](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/background/architecture.md).  - The [Kubeapps Developer Documentation](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/reference/developer/README.md) for instructions on setting up the developer environment for developing on Kubeapps and its components.  - The [Kubeapps Build Guide](https://github.com/vmware-tanzu/kubeapps/blob/main/site/content/docs/latest/reference/developer/build.md) for instructions on setting up the build environment and building Kubeapps from source.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1PackageMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'media_type': 'str',
        'artifact_type': 'str',
        'digest': 'str',
        'name': 'str',
        'description': 'str',
        'url': 'str'
    }

    attribute_map = {
        'media_type': 'mediaType',
        'artifact_type': 'artifactType',
        'digest': 'digest',
        'name': 'name',
        'description': 'description',
        'url': 'url'
    }

    def __init__(self, media_type=None, artifact_type=None, digest=None, name=None, description=None, url=None):  # noqa: E501
        """V1alpha1PackageMetadata - a model defined in Swagger"""  # noqa: E501
        self._media_type = None
        self._artifact_type = None
        self._digest = None
        self._name = None
        self._description = None
        self._url = None
        self.discriminator = None
        if media_type is not None:
            self.media_type = media_type
        if artifact_type is not None:
            self.artifact_type = artifact_type
        if digest is not None:
            self.digest = digest
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if url is not None:
            self.url = url

    @property
    def media_type(self):
        """Gets the media_type of this V1alpha1PackageMetadata.  # noqa: E501

        Media type of this metadata  # noqa: E501

        :return: The media_type of this V1alpha1PackageMetadata.  # noqa: E501
        :rtype: str
        """
        return self._media_type

    @media_type.setter
    def media_type(self, media_type):
        """Sets the media_type of this V1alpha1PackageMetadata.

        Media type of this metadata  # noqa: E501

        :param media_type: The media_type of this V1alpha1PackageMetadata.  # noqa: E501
        :type: str
        """

        self._media_type = media_type

    @property
    def artifact_type(self):
        """Gets the artifact_type of this V1alpha1PackageMetadata.  # noqa: E501

        Artifact type of this metadata  # noqa: E501

        :return: The artifact_type of this V1alpha1PackageMetadata.  # noqa: E501
        :rtype: str
        """
        return self._artifact_type

    @artifact_type.setter
    def artifact_type(self, artifact_type):
        """Sets the artifact_type of this V1alpha1PackageMetadata.

        Artifact type of this metadata  # noqa: E501

        :param artifact_type: The artifact_type of this V1alpha1PackageMetadata.  # noqa: E501
        :type: str
        """

        self._artifact_type = artifact_type

    @property
    def digest(self):
        """Gets the digest of this V1alpha1PackageMetadata.  # noqa: E501

        Digest of this metadata  # noqa: E501

        :return: The digest of this V1alpha1PackageMetadata.  # noqa: E501
        :rtype: str
        """
        return self._digest

    @digest.setter
    def digest(self, digest):
        """Sets the digest of this V1alpha1PackageMetadata.

        Digest of this metadata  # noqa: E501

        :param digest: The digest of this V1alpha1PackageMetadata.  # noqa: E501
        :type: str
        """

        self._digest = digest

    @property
    def name(self):
        """Gets the name of this V1alpha1PackageMetadata.  # noqa: E501

        Human readable name for this metadata.  # noqa: E501

        :return: The name of this V1alpha1PackageMetadata.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1alpha1PackageMetadata.

        Human readable name for this metadata.  # noqa: E501

        :param name: The name of this V1alpha1PackageMetadata.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this V1alpha1PackageMetadata.  # noqa: E501

        Human readable description for this metadata.  # noqa: E501

        :return: The description of this V1alpha1PackageMetadata.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this V1alpha1PackageMetadata.

        Human readable description for this metadata.  # noqa: E501

        :param description: The description of this V1alpha1PackageMetadata.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def url(self):
        """Gets the url of this V1alpha1PackageMetadata.  # noqa: E501

        The url reference for this metadata.  # noqa: E501

        :return: The url of this V1alpha1PackageMetadata.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this V1alpha1PackageMetadata.

        The url reference for this metadata.  # noqa: E501

        :param url: The url of this V1alpha1PackageMetadata.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1PackageMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1PackageMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
