# coding: utf-8

"""
    Kubeapps API

    [![CircleCI](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main.svg?style=svg)](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main)   [Kubeapps](https://github.com/vmware-tanzu/kubeapps) is a web-based UI for deploying and managing applications in Kubernetes clusters.   Note: this API documentation is still in an initial stage and is subject to change. Before coupling to it, please [drop us an issue](https://github.com/vmware-tanzu/kubeapps/issues/new/choose) or reach us [via Slack](https://kubernetes.slack.com/messages/kubeapps) to know more about your use case and see how we can assist you.  #### Developer Documentation  - The [Kubeapps Architecture Overview](https://kubeapps.dev/docs/latest/background/architecture/).  - The [Kubeapps Developer Documentation](https://kubeapps.dev/docs/latest/reference/developer/) for instructions on setting up the developer environment for developing on Kubeapps and its components.  - The [Kubeapps Build Guide](https://kubeapps.dev/docs/latest/reference/developer/build/) for instructions on setting up the build environment and building Kubeapps from source.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1PackageRepositoryTlsConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'insecure_skip_verify': 'bool',
        'cert_authority': 'str',
        'secret_ref': 'V1alpha1SecretKeyReference'
    }

    attribute_map = {
        'insecure_skip_verify': 'insecureSkipVerify',
        'cert_authority': 'certAuthority',
        'secret_ref': 'secretRef'
    }

    def __init__(self, insecure_skip_verify=None, cert_authority=None, secret_ref=None):  # noqa: E501
        """V1alpha1PackageRepositoryTlsConfig - a model defined in Swagger"""  # noqa: E501
        self._insecure_skip_verify = None
        self._cert_authority = None
        self._secret_ref = None
        self.discriminator = None
        if insecure_skip_verify is not None:
            self.insecure_skip_verify = insecure_skip_verify
        if cert_authority is not None:
            self.cert_authority = cert_authority
        if secret_ref is not None:
            self.secret_ref = secret_ref

    @property
    def insecure_skip_verify(self):
        """Gets the insecure_skip_verify of this V1alpha1PackageRepositoryTlsConfig.  # noqa: E501


        :return: The insecure_skip_verify of this V1alpha1PackageRepositoryTlsConfig.  # noqa: E501
        :rtype: bool
        """
        return self._insecure_skip_verify

    @insecure_skip_verify.setter
    def insecure_skip_verify(self, insecure_skip_verify):
        """Sets the insecure_skip_verify of this V1alpha1PackageRepositoryTlsConfig.


        :param insecure_skip_verify: The insecure_skip_verify of this V1alpha1PackageRepositoryTlsConfig.  # noqa: E501
        :type: bool
        """

        self._insecure_skip_verify = insecure_skip_verify

    @property
    def cert_authority(self):
        """Gets the cert_authority of this V1alpha1PackageRepositoryTlsConfig.  # noqa: E501


        :return: The cert_authority of this V1alpha1PackageRepositoryTlsConfig.  # noqa: E501
        :rtype: str
        """
        return self._cert_authority

    @cert_authority.setter
    def cert_authority(self, cert_authority):
        """Sets the cert_authority of this V1alpha1PackageRepositoryTlsConfig.


        :param cert_authority: The cert_authority of this V1alpha1PackageRepositoryTlsConfig.  # noqa: E501
        :type: str
        """

        self._cert_authority = cert_authority

    @property
    def secret_ref(self):
        """Gets the secret_ref of this V1alpha1PackageRepositoryTlsConfig.  # noqa: E501


        :return: The secret_ref of this V1alpha1PackageRepositoryTlsConfig.  # noqa: E501
        :rtype: V1alpha1SecretKeyReference
        """
        return self._secret_ref

    @secret_ref.setter
    def secret_ref(self, secret_ref):
        """Sets the secret_ref of this V1alpha1PackageRepositoryTlsConfig.


        :param secret_ref: The secret_ref of this V1alpha1PackageRepositoryTlsConfig.  # noqa: E501
        :type: V1alpha1SecretKeyReference
        """

        self._secret_ref = secret_ref

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1PackageRepositoryTlsConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1PackageRepositoryTlsConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
