# coding: utf-8

"""
    Kubeapps API

    [![CircleCI](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main.svg?style=svg)](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main)   [Kubeapps](https://github.com/vmware-tanzu/kubeapps) is a web-based UI for deploying and managing applications in Kubernetes clusters.   Note: this API documentation is still in an initial stage and is subject to change. Before coupling to it, please [drop us an issue](https://github.com/vmware-tanzu/kubeapps/issues/new/choose) or reach us [via Slack](https://kubernetes.slack.com/messages/kubeapps) to know more about your use case and see how we can assist you.  #### Developer Documentation  - The [Kubeapps Architecture Overview](https://kubeapps.dev/docs/latest/background/architecture/).  - The [Kubeapps Developer Documentation](https://kubeapps.dev/docs/latest/reference/developer/) for instructions on setting up the developer environment for developing on Kubeapps and its components.  - The [Kubeapps Build Guide](https://kubeapps.dev/docs/latest/reference/developer/build/) for instructions on setting up the build environment and building Kubeapps from source.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1PackageRepositorySummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'package_repo_ref': 'V1alpha1PackageRepositoryReference',
        'name': 'str',
        'description': 'str',
        'namespace_scoped': 'bool',
        'type': 'str',
        'url': 'str',
        'status': 'V1alpha1PackageRepositoryStatus',
        'requires_auth': 'bool'
    }

    attribute_map = {
        'package_repo_ref': 'packageRepoRef',
        'name': 'name',
        'description': 'description',
        'namespace_scoped': 'namespaceScoped',
        'type': 'type',
        'url': 'url',
        'status': 'status',
        'requires_auth': 'requiresAuth'
    }

    def __init__(self, package_repo_ref=None, name=None, description=None, namespace_scoped=None, type=None, url=None, status=None, requires_auth=None):  # noqa: E501
        """V1alpha1PackageRepositorySummary - a model defined in Swagger"""  # noqa: E501
        self._package_repo_ref = None
        self._name = None
        self._description = None
        self._namespace_scoped = None
        self._type = None
        self._url = None
        self._status = None
        self._requires_auth = None
        self.discriminator = None
        if package_repo_ref is not None:
            self.package_repo_ref = package_repo_ref
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if namespace_scoped is not None:
            self.namespace_scoped = namespace_scoped
        if type is not None:
            self.type = type
        if url is not None:
            self.url = url
        if status is not None:
            self.status = status
        if requires_auth is not None:
            self.requires_auth = requires_auth

    @property
    def package_repo_ref(self):
        """Gets the package_repo_ref of this V1alpha1PackageRepositorySummary.  # noqa: E501


        :return: The package_repo_ref of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :rtype: V1alpha1PackageRepositoryReference
        """
        return self._package_repo_ref

    @package_repo_ref.setter
    def package_repo_ref(self, package_repo_ref):
        """Sets the package_repo_ref of this V1alpha1PackageRepositorySummary.


        :param package_repo_ref: The package_repo_ref of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :type: V1alpha1PackageRepositoryReference
        """

        self._package_repo_ref = package_repo_ref

    @property
    def name(self):
        """Gets the name of this V1alpha1PackageRepositorySummary.  # noqa: E501


        :return: The name of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1alpha1PackageRepositorySummary.


        :param name: The name of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this V1alpha1PackageRepositorySummary.  # noqa: E501

        A user-provided description.  # noqa: E501

        :return: The description of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this V1alpha1PackageRepositorySummary.

        A user-provided description.  # noqa: E501

        :param description: The description of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def namespace_scoped(self):
        """Gets the namespace_scoped of this V1alpha1PackageRepositorySummary.  # noqa: E501

        Whether this repository is global or namespace-scoped.  # noqa: E501

        :return: The namespace_scoped of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :rtype: bool
        """
        return self._namespace_scoped

    @namespace_scoped.setter
    def namespace_scoped(self, namespace_scoped):
        """Sets the namespace_scoped of this V1alpha1PackageRepositorySummary.

        Whether this repository is global or namespace-scoped.  # noqa: E501

        :param namespace_scoped: The namespace_scoped of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :type: bool
        """

        self._namespace_scoped = namespace_scoped

    @property
    def type(self):
        """Gets the type of this V1alpha1PackageRepositorySummary.  # noqa: E501


        :return: The type of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V1alpha1PackageRepositorySummary.


        :param type: The type of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def url(self):
        """Gets the url of this V1alpha1PackageRepositorySummary.  # noqa: E501

        URL identifying the package repository location.  # noqa: E501

        :return: The url of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this V1alpha1PackageRepositorySummary.

        URL identifying the package repository location.  # noqa: E501

        :param url: The url of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def status(self):
        """Gets the status of this V1alpha1PackageRepositorySummary.  # noqa: E501


        :return: The status of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :rtype: V1alpha1PackageRepositoryStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V1alpha1PackageRepositorySummary.


        :param status: The status of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :type: V1alpha1PackageRepositoryStatus
        """

        self._status = status

    @property
    def requires_auth(self):
        """Gets the requires_auth of this V1alpha1PackageRepositorySummary.  # noqa: E501

        existence of any authentication parameters for connecting to a repository.  # noqa: E501

        :return: The requires_auth of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :rtype: bool
        """
        return self._requires_auth

    @requires_auth.setter
    def requires_auth(self, requires_auth):
        """Sets the requires_auth of this V1alpha1PackageRepositorySummary.

        existence of any authentication parameters for connecting to a repository.  # noqa: E501

        :param requires_auth: The requires_auth of this V1alpha1PackageRepositorySummary.  # noqa: E501
        :type: bool
        """

        self._requires_auth = requires_auth

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1PackageRepositorySummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1PackageRepositorySummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
