# coding: utf-8

"""
    Kubeapps API

    [![CircleCI](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main.svg?style=svg)](https://circleci.com/gh/vmware-tanzu/kubeapps/tree/main)   [Kubeapps](https://github.com/vmware-tanzu/kubeapps) is a web-based UI for deploying and managing applications in Kubernetes clusters.   Note: this API documentation is still in an initial stage and is subject to change. Before coupling to it, please [drop us an issue](https://github.com/vmware-tanzu/kubeapps/issues/new/choose) or reach us [via Slack](https://kubernetes.slack.com/messages/kubeapps) to know more about your use case and see how we can assist you.  #### Developer Documentation  - The [Kubeapps Architecture Overview](https://kubeapps.dev/docs/latest/background/architecture/).  - The [Kubeapps Developer Documentation](https://kubeapps.dev/docs/latest/reference/developer/) for instructions on setting up the developer environment for developing on Kubeapps and its components.  - The [Kubeapps Build Guide](https://kubeapps.dev/docs/latest/reference/developer/build/) for instructions on setting up the build environment and building Kubeapps from source.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1SshCredentials(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'private_key': 'str',
        'known_hosts': 'str'
    }

    attribute_map = {
        'private_key': 'privateKey',
        'known_hosts': 'knownHosts'
    }

    def __init__(self, private_key=None, known_hosts=None):  # noqa: E501
        """V1alpha1SshCredentials - a model defined in Swagger"""  # noqa: E501
        self._private_key = None
        self._known_hosts = None
        self.discriminator = None
        if private_key is not None:
            self.private_key = private_key
        if known_hosts is not None:
            self.known_hosts = known_hosts

    @property
    def private_key(self):
        """Gets the private_key of this V1alpha1SshCredentials.  # noqa: E501


        :return: The private_key of this V1alpha1SshCredentials.  # noqa: E501
        :rtype: str
        """
        return self._private_key

    @private_key.setter
    def private_key(self, private_key):
        """Sets the private_key of this V1alpha1SshCredentials.


        :param private_key: The private_key of this V1alpha1SshCredentials.  # noqa: E501
        :type: str
        """

        self._private_key = private_key

    @property
    def known_hosts(self):
        """Gets the known_hosts of this V1alpha1SshCredentials.  # noqa: E501

        known hosts.  # noqa: E501

        :return: The known_hosts of this V1alpha1SshCredentials.  # noqa: E501
        :rtype: str
        """
        return self._known_hosts

    @known_hosts.setter
    def known_hosts(self, known_hosts):
        """Sets the known_hosts of this V1alpha1SshCredentials.

        known hosts.  # noqa: E501

        :param known_hosts: The known_hosts of this V1alpha1SshCredentials.  # noqa: E501
        :type: str
        """

        self._known_hosts = known_hosts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1SshCredentials, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1SshCredentials):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
